### ISSUE TITLE
Can't catch errors

### ISSUE THREAD

**Issue by paulsutherland** [gawsoftpl/grpc-js-reflection-api-client#3]
Hi,

How do you catch errors?

I am trying to handles a situation where an incorrect ip address has been provided. I want to catch the error and report it back.

If I run this code and the the ip address is wrong, for example the wrong ip address was provided, I expected the try catch would catch the error and I could handle it:

```
const { GrpcReflection } = require('grpc-js-reflection-client');
const grpc =  require('@grpc/grpc-js');

/**
 * List services
 */
try {
    (async () => {
        const c = new GrpcReflection('0.0.0.0:50051', grpc.credentials.createInsecure());
        console.log(await c.listServices());
    })();

} catch(e){
    console.log(e);
}
```

If you run this and there is no service running on 0.0.0.0:50051 it throws:

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: 14 UNAVAILABLE: No connection established
    at callErrorFromStatus (/Users/Paul/Spikes/grpc-reflection-test/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/Users/Paul/Spikes/grpc-reflection-test/node_modules/@grpc/grpc-js/build/src/client.js:419:73)
    at Object.onReceiveStatus (/Users/Paul/Spikes/grpc-reflection-test/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /Users/Paul/Spikes/grpc-reflection-test/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeBidiStreamRequest (/Users/Paul/Spikes/grpc-reflection-test/node_modules/@grpc/grpc-js/build/src/client.js:403:32)
    at ServiceClientImpl.<anonymous> (/Users/Paul/Spikes/grpc-reflection-test/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /Users/Paul/Spikes/grpc-reflection-test/node_modules/grpc-js-reflection-client/dist/GrpcReflection.js:43:38
    at new Promise (<anonymous>)
    at GrpcReflection.request (/Users/Paul/Spikes/grpc-reflection-test/node_modules/grpc-js-reflection-client/dist/GrpcReflection.js:42:16)
    at GrpcReflection.listServices (/Users/Paul/Spikes/grpc-reflection-test/node_modules/grpc-js-reflection-client/dist/GrpcReflection.js:19:37)
    at /Users/Paul/Spikes/grpc-reflection-test/index.js:10:25
    at Object.<anonymous> (/Users/Paul/Spikes/grpc-reflection-test/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
Emitted 'error' event on ClientDuplexStreamImpl instance at:
    at Object.onReceiveStatus (/Users/Paul/Spikes/grpc-reflection-test/node_modules/@grpc/grpc-js/build/src/client.js:419:28)
    at Object.onReceiveStatus (/Users/Paul/Spikes/grpc-reflection-test/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /Users/Paul/Spikes/grpc-reflection-test/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 14,
  details: 'No connection established',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

The catch does not handle the error and the program dies.

Any help would be appreciated.

Thanks,

Paul

**Comment by gawsoftpl** [comment]
I had a similar error with dns resolve. I think that this is an error from the internal nodejs network package. I think that you have to write catch for  Unhandled 'error' event

```js
process.on('uncaughtException', function (err) {
    //do something
});
```

**Comment by pkvenu** [comment]
I am also running into the same issue mentioned above. When I try using grpcurl to connect to my grpc service, I am able to get the list of all the services, but when I try from localhost using the node application it gives me the error. 
```

const express = require("express");
const { GrpcReflection } = require('grpc-js-reflection-client');
const process = require('process');
var fs = require('fs');
const grpc =  require('@grpc/grpc-js');
const app = express();
app.use(express.json());
const PORT = process.env.PORT || 3000;

app.listen(PORT,() =>{
    console.log("server running on port:", PORT);
    process.on('uncaughtException', (error, source) => {

        fs.writeSync(
            process.stderr.fd,
            `Caught exception: ${error}\n` +
            `Exception origin: ${source}`
          );
        
        });
    try {
        (async()=> {
            const client = new GrpcReflection('gateway.grpc.com:443', grpc.credentials.createInsecure());
            console.log(await client.listServices());
        })();
    }catch(e){
        console.log(e)
    }
});
```

**Result:**

`Error: 14 UNAVAILABLE: read ECONNRESET`

**Comment by gawsoftpl** [comment]
@pkvenu you have sent an example for your example grpc server client example, please paste the example for localhost. Please send more info about your localhost grpc server. To resolve your issue, you need to paste grpc server code.

**Comment by gawsoftpl** [comment]
@paulsutherland I fixed your issue, I will create new release for catch all errors

**Comment by gawsoftpl** [comment]
@pkvenu which version of grpc reflection do you use in v1 or v1alpha

**Comment by gawsoftpl** [comment]
@pkvenu Install new version of my library 1.2.1

I tested grpc with tls for grpcb.in, everything works fine

```js
const { GrpcReflection } = require('grpc-js-reflection-client');
const grpc =  require('@grpc/grpc-js');

function getChannelCredentials() {
    return grpc.ChannelCredentials.createSsl();
}

try {
    (async()=> {
        const client = new GrpcReflection(
            'grpcb.in:9001',
            getChannelCredentials(),

        );
        console.log(await client.listServices());
    })();
}catch(e){
    console.log(e)
}

```

Try adjust settings for your endpoint *****, I see that you have gateway, maybe there is a timeout in your load balancer

```js
const { GrpcReflection } = require('grpc-js-reflection-client');
const grpc =  require('@grpc/grpc-js');

function getChannelCredentials() {
    return grpc.ChannelCredentials.createSsl();
}
try {
    (async()=> {
        const client = new GrpcReflection(
            '***********',
            getChannelCredentials(),
            {
                "grpc.max_connection_age_ms": 10*1000,
                'grpc.keepalive_time_ms': 10 * 1000,
                // Keepalive ping timeout after 5 seconds, default is 20 seconds.
                'grpc.keepalive_timeout_ms': 5 * 1000,
                // Allow keepalive pings when there are no gRPC calls.
                'grpc.keepalive_permit_without_calls': 1,
                "grpc.initial_reconnect_backoff_ms": 1000,
            }
        );
        console.log(await client.listServices());
    })();
}catch(e){
    console.log(e)
}
```

Run command with verbosity
```sh
GRPC_VERBOSITY=debug GRPC_TRACE=channel,subchannel,call_stream node ea.example.js
```

**Comment by pkvenu** [comment]
Thanks, @gawsoftpl for the quick update. I tried using your example above:
host = grpcb.in:9001 - Works perfectly.
host = gateway.grpc.com:443 - Recevie Transient Failure error. 



```
const express = require("express");
const { GrpcReflection } = require('grpc-js-reflection-client');
const process = require('process');
var fs = require('fs');
const grpc =  require('@grpc/grpc-js');

const app = express();
app.use(express.json());


const PORT = process.env.PORT || 3000;
const HOST = "grpcb.in:9001";


function getChannelCredentials(){
    return grpc.ChannelCredentials.createSsl();
}

function getServiceList(host){
    console.log("HOST is: " + host);
    try {
        (async()=> {
            const client = new GrpcReflection(
                host, 
                getChannelCredentials(),
                { 
                    "grpc.max_connection_age_ms": 10*1000,
                    'grpc.keepalive_time_ms': 10 * 1000,
                    // Keepalive ping timeout after 5 seconds, default is 20 seconds.
                    'grpc.keepalive_timeout_ms': 5 * 1000,
                    // Allow keepalive pings when there are no gRPC calls.
                    'grpc.keepalive_permit_without_calls': 1,
                    "grpc.initial_reconnect_backoff_ms": 1000,
                }
            );
            console.log(await client.listServices());
        })();
    }catch(e){
        console.log(e)
    }
}


app.listen(PORT,() =>{
    console.log("server running on port:", PORT);
    getServiceList(HOST1);
   
});

```



Attached is the package.json 

```
{
  "name": "grpc-server",
  "version": "1.0.0",
  "description": "Sample server to get grpc reflection objects using nodejs",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "grpc",
    "server-reflection"
  ],
  "author": "pawan",
  "license": "ISC",
  "dependencies": {
    "@grpc/grpc-js": "^1.8.17",
    "express": "^4.18.2",
    "fs": "^0.0.1-security",
    "grpc-js-reflection-client": "^1.2.1",
    "grpc-reflection-js": "^0.1.2",
    "lodash": "^4.17.21",
    "process": "^0.11.10"
  }
}

```

When I try using grpcurl, I get the results as expected. I have not changed anything on the server side. I am trying to understand why nodejs keep giving me this error.

**Comment by pkvenu** [comment]
@gawsoftpl - I was able to finally get it work by downgrading my node version to v16 from v20. Thankyou so much for the help. Also in the example folder, there is an ea example, if you could remove the grpc host URL that would really help.

**Comment by gawsoftpl** [comment]
Example removed

**Comment by pkvenu** [comment]
Thanks, @gawsoftpl for all the help. Also one last question is there any method to get a list of all methods from a service? Similar to the image attached.

**Comment by paulsutherland** [comment]
@gawsoftpl 

Thanks for taking the time to look into this.  I can see the changes you made and you are now listening for an error and throwing an exception.

I tried it out on this simple example where the IP address has nothing on the end of it, but it did not catch the error.  

Do I need to subscribe/listen to the error event instead?

```
try {
  (async () => {
    const c = new GrpcReflection('0.0.0.0:9000', grpc.credentials.createInsecure())
    console.log(await c.listServices())
  })()

} catch(e){
  <<<Was hoping this would catch the Uncaught Error: Error: 14 UNAVAILABLE: No connection established>>>
  console.log("Catch error here", e)
}
```

Also tried this with the same result.

```
const c = new GrpcReflection('0.0.0.0:9000', grpc.credentials.createInsecure())
c.listServices()
  .then((services) => {
    console.log('Services', services)
  })
  .catch((err) => {
   <<<Was hoping this would catch the Uncaught Error: Error: 14 UNAVAILABLE: No connection established>>>
    console.log('Error', err)
  })
```

Using version 1.2.2

**Comment by gawsoftpl** [comment]
@paulsutherland fixed, try version 1.2.3

**Comment by gawsoftpl** [comment]
@pkvenu I added new feature listMethods. Try version 1.2.4 
```js
const grpc =  require('@grpc/grpc-js');

const { GrpcReflection } = require('grpc-js-reflection-client');


function getChannelCredentials(){
    return grpc.ChannelCredentials.createSsl();
}


const client = new GrpcReflection('***********', getChannelCredentials())
client.listMethods('************').then(methods => {
  console.log(methods.map(m => m.name));
});

```

**Comment by pkvenu** [comment]
Hi @gawsoftpl, 

Thank you so much for adding the list Method functionality. It's a lifesaver and keeps my code cleaner. I was wondering if you could add another functionality to the package to list the input and output properties for these methods. 

Ideally, it would be great to pass the method name and get both the input and output values in one call.

**Comment by gawsoftpl** [comment]
@pkvenu I don't understand you. RequestType and ResponseType are already implemented. Have you read the source code?

[ListMethods](https://github.com/gawsoftpl/grpc-js-reflection-api-client/blob/main/src/GrpcReflection.ts#L72)

ListMethods return an object of the method name and full definition

```js
const methods = await client.listMethods('grpc.gateway.examples.examplepb.ABitOfEverythingService');
console.log(methods.map(method => method.definition.requestType));
console.log(methods.map(method => method.definition.responseType));
```

**Comment by paulsutherland** [comment]
@gawsoftpl Hi, I tried 1.2.3 and it worked as expected.

Thank you for taking time to update your work, this is a great library.

I think this issue has grown in a couple of directions, but from the side of "Can't catch errors", I would say that issue is now resolved and closed.

Cheers...

Paul

**Comment by pkvenu** [comment]
@gawsoftpl - Thanks for the great package once again. 

I tried the list method and looked at the response. The only properties I see are as per the screenshot. The requestType and responseType objects are missing. 

<img width="863" alt="Screenshot 2023-07-17 at 4 52 18 AM" src="https://github.com/gawsoftpl/grpc-js-reflection-api-client/assets/6444752/bec272d3-9b3f-4cf7-8a2b-4706d7e27f06">

But when I do a 
`console.log(methods.map(method => method.definition));
`
I can see the requestType and responseType as properties for  **"method.definition"**

```
{
    path: '/hello.HelloService/SayHello',
    requestStream: false,
    responseStream: false,
    requestSerialize: [Function: serialize],
    requestDeserialize: [Function: deserialize],
    responseSerialize: [Function: serialize],
    responseDeserialize: [Function: deserialize],
    originalName: 'sayHello',
    requestType: {
      format: 'Protocol Buffer 3 DescriptorProto',
      type: [Object],
      fileDescriptorProtos: [Array]
    },
    responseType: {
      format: 'Protocol Buffer 3 DescriptorProto',
      type: [Object],
      fileDescriptorProtos: [Array]
    }
  },
```

**Comment by gawsoftpl** [comment]
I changed the interface for listmethod from clientMethod to MethodDefinition. That interface has RequestType and responseType. Should help.

**Comment by pkvenu** [comment]
@gawsoftpl - Can you provide me with an example usage? I am still not able to get the requestType and responseType.

**Comment by gawsoftpl** [comment]
Have you installed new version 1.2.5 ?

```js
const grpc =  require('@grpc/grpc-js');

const { GrpcReflection } = require('grpc-js-reflection-client');

function getChannelCredentials(){
    return grpc.ChannelCredentials.createSsl();
}

const client = new GrpcReflection('**************', getChannelCredentials())
client.listMethods('************').then(methods => {
    console.log(methods.map(m => m.definition.requestType));
});
```

**Comment by pkvenu** [comment]
Yes. Have installed the new version. Below is the screenshot. 

<img width="1696" alt="Screenshot 2023-07-17 at 4 36 54 PM" src="https://github.com/gawsoftpl/grpc-js-reflection-api-client/assets/6444752/7d19a3bc-a02d-48e3-af19-b71314d3e2f6">

**Comment by gawsoftpl** [comment]
I tested it and in my IDE I have requestType and responseType. Please create a new project and check for a temporary grpc project.

**Comment by pkvenu** [comment]
For some reason, the old project was not displaying the methods. I am now able to view them and use them accordingly.

Thankyou once again for the great package and all your help.
